# Site settings
title: Vince Konigan
email: info@vincekonigan.com
# -- Dev configs: --
# url: 
# baseurl: /
# --Production configs:-- 
url: ericmadethat.com
baseurl: /vincekonigan
description: "Musicien basé à Montréal"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Vince Konigan

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: soundcloud
    url: https://soundcloud.com/vince-konigan/
  - title: bandcamp
    url: https://vincekonigan.bandcamp.com/

# Build settings
markdown: kramdown
permalink: pretty
